version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/test/wasm-smoke-test"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      duckdb-ecosystem:
        patterns:
          - "duckdb"
          - "extension-ci-tools"
